import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-gray-50 text-gray-900 min-h-screen">
        <header className="bg-white shadow py-4 px-6">
          <nav className="max-w-4xl mx-auto flex justify-between items-center">
            <h1 className="font-bold text-lg">🍻 BarApp</h1>
            <div className="space-x-4">
              <Link href="/" className="text-blue-600 hover:underline">
                Home
              </Link>
              <Link href="/orders" className="text-blue-600 hover:underline">
                Órdenes
              </Link>
            </div>
          </nav>
        </header>
        <main className="max-w-4xl mx-auto mt-6">{children}</main>
        <footer className="text-center text-sm text-gray-500 mt-10 mb-4">
          &copy; 2025 BarApp. Todos los derechos reservados.
        </footer>
      </body>
    </html>
  );
}
