import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import { ToastProvider } from '@/context/ToastContext';

export const metadata: Metadata = {
  title: 'BarApp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-gray-50 text-gray-800 min-h-screen font-sans flex flex-col">
        <header className="bg-white shadow-md py-4 px-6">
          <nav className="max-w-4xl mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold text-red-500 flex items-center space-x-2">
              <img src="/images/cometa-bar.png" alt="Logo" className="h-12 w-12" />
              <span>Cometa Bar</span>
            </h1>
            <div className="space-x-4">
              <Link
                href="/"
                className="text-gray-700 font-medium hover:text-red-500 transition-colors"
              >
                Home
              </Link>
              <Link
                href="/orders"
                className="text-gray-700 font-medium hover:text-red-500 transition-colors"
              >
                Órdenes
              </Link>
            </div>
          </nav>
        </header>

        <main className="flex-1 max-w-4xl mx-auto w-full px-4 py-6">
          <ToastProvider>{children}</ToastProvider>
        </main>

        <footer className="bg-white border-t text-center text-sm text-gray-500 py-6 mt-10">
          &copy; 2025 Cometa Bar. Todos los derechos reservados.
        </footer>
      </body>
    </html>
  );
}